# ============================================================
# DOCKER COMPOSE - Infrastructure de traitement de votes
# ============================================================
name: election-streaming
services:

  # ==========================================================
  # 1. KAFKA - Broker de messages en mode KRaft
  # ==========================================================
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk=="
      
      # ===== AJOUT POUR KRaft =====
      # Donner plus de temps pour le démarrage
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
      KAFKA_TOOLS_LOG4J_LOGLEVEL: INFO

    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - election-net

  # ==========================================================
  # 2. KAFKA UI - Interface Web de Monitoring
  # ==========================================================
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: election-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - election-net

  # ==========================================================
  # 3. PRODUCER - Producteur Python de votes
  # ==========================================================
  producer:
    build:
      context: ./producer
    container_name: election-producer
    restart: on-failure
    environment:
      KAFKA_SERVER: kafka:9092
      KAFKA_TOPIC: ${KAFKA_TOPIC}
    volumes:
      - ./producer/app:/app
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - election-net

  # ==========================================================
  # 4. SPARK MASTER - Apache Spark officiel
  # ==========================================================
  # ==========================================================
  # SPARK MASTER
  # ==========================================================
  spark-master:
    image: apache/spark:3.5.1
    container_name: election-spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master

    environment:
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
      HOME: /tmp

    ports:
      - "7077:7077"
      - "8081:8080"

    volumes:
      - spark_ivy:/tmp/.ivy2

    networks:
      - election-net



  # ==========================================================
  # SPARK WORKER
  # ==========================================================
  spark-worker:
    image: apache/spark:3.5.1
    container_name: election-spark-worker

    depends_on:
      - spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077

    environment:
      SPARK_WORKER_MEMORY: 2G
      SPARK_WORKER_CORES: 2
      HOME: /tmp

    volumes:
      - spark_ivy:/tmp/.ivy2

    networks:
      - election-net



  # ==========================================================
  # SPARK STREAMING APP
  # ==========================================================
  spark-app:
    build:
      context: ./spark

    container_name: election-spark-app

    depends_on:
      - kafka
      - postgres
      - minio
      - spark-master
      - spark-worker

    environment:
      HOME: /tmp

      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: votes

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: votes

    volumes:
      - ./spark/app:/app
      - spark_ivy:/tmp/.ivy2
      - spark_checkpoints:/app/checkpoints

    networks:
      - election-net
  # ==========================================================
  # 6. POSTGRESQL - Base de données
  # ==========================================================
  postgres:
    image: postgres:16
    container_name: postgres-election
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - election-net

  pgadmin:
    image: dpage/pgadmin4

    container_name: pgadmin

    ports:
      - "5050:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

    depends_on:
      - postgres

    networks:
      - election-net

  # ==========================================================
  # 7. MINIO - Stockage d'objets (Data Lake)
  # ==========================================================
  minio:
    image: minio/minio
    container_name: minio-election
    restart: always
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    networks:
      - election-net


  mc:
    image: minio/mc

    depends_on:
      - minio

    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set local http://minio:9000 admin@election.sn password;
      mc mb local/votes;
      exit 0;
      "

    networks:
      - election-net



  dashboard:
    build:
      context: ./dashboard

    container_name: election-dashboard

    ports:
      - "8501:8501"

    depends_on:
      - postgres

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - election-net

# ============================================================
# VOLUMES PERSISTANTS
# ============================================================
volumes:
  postgres_data:
  minio_data:
  spark_ivy:
  spark_checkpoints:

# ============================================================
# RÉSEAU
# ============================================================
networks:
  election-net:
    driver: bridge